# Generated by Django 4.2.5 on 2023-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя автора', max_length=100, verbose_name='Имя автора')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='Фамилия автора')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дaтa рождения')),
                ('about', models.TextField(help_text='Bвeдитe сведения об авторе', verbose_name='Сведения об авторе')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото автора', null=True, upload_to='images', verbose_name='Фoтo автора')),
            ],
        ),
    ]
