# Generated by Django 4.2.5 on 2023-09-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=200, verbose_name='Haзвaниe книги')),
                ('genre', models.ForeignKey(help_text=' Выберите жанр для книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр книги')),
                ('language', models.ForeignKey(help_text='Выберите язык книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Язык книги')),
                ('publisher', models.ForeignKey(help_text='Выберите издательство', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.publisher', verbose_name='Издательство')),
            ],
        ),
    ]
