# Generated by Django 4.2.5 on 2023-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(help_text='Введите год названия', max_length=20, verbose_name='Год издания'),
        ),
    ]
