# Generated by Django 4.2.5 on 2023-10-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.ForeignKey(help_text='Введите краткое описание книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.summary', verbose_name='Описание книги'),
        ),
    ]
