# Generated by Django 4.2.5 on 2023-10-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену книги', max_digits=7, null=True),
        ),
    ]
