# Generated by Django 4.2.5 on 2023-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(help_text='Введите изображение обложки', upload_to='images', verbose_name='Изображение обложки')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(help_text='Введите изображение обложки', null=True, upload_to='images', verbose_name='Изображение обложки'),
        ),
    ]
