# Generated by Django 4.2.5 on 2023-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_book_summary_alter_summary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(help_text='Введите год названия', max_length=4, null=True, verbose_name='Год издания'),
        ),
    ]
