# Generated by Django 4.2.5 on 2023-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Должно содержать 13 символов', max_length=13, null=True, verbose_name='ISBN книги'),
        ),
    ]
