# Generated by Django 4.2.5 on 2023-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену книги', max_digits=7, verbose_name='Цeнa (руб.'),
        ),
    ]
